name: drawing_board
description: "Flutter project for drawing geometry primitives on your device."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  cupertino_icons: ^1.0.2
  business:
    path: ./packages/business
  model:
    path: ./packages/model

dev_dependencies:
  flutter_test:
    sdk: flutter

  analyzer_sm:
    path: ./packages/analyzer_sm

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
